### ISSUE TITLE
Cannot get node-red-contrib-openzwave-am to run.

### ISSUE THREAD

**Issue by Tazintosh** [appmodule/node-red-contrib-openzwave-am#4]
Good evening folks,

When I try to install "node-red-contrib-openzwave-am" using the palette manager, I've the following issue. (Note the same problem exit by installing from `npm install node-red-contrib-openzwave-am`

```
21 Nov 19:45:00 - [info] Installing module: node-red-contrib-openzwave-am, version: 1.5.6
21 Nov 19:47:00 - [info] Installed module: node-red-contrib-openzwave-am
21 Nov 19:47:00 - [info] Added node types:
21 Nov 19:47:00 - [info] - node-red-contrib-openzwave-am:zwave-controller : TypeError: require(...).getMac is not a function (line:30)
21 Nov 19:47:00 - [info] - node-red-contrib-openzwave-am:zwave-in : TypeError: require(...).getMac is not a function (line:30)
21 Nov 19:47:00 - [info] - node-red-contrib-openzwave-am:zwave-out : TypeError: require(...).getMac is not a function (line:30)
```
I'm running the following:
Node-RED version: v0.20.7 (installed with `npm install -g --unsafe-perm node-red`)
Node.js version: v10.16.3
Darwin 17.7.0 x64 LE

Same issue with 
Node-RED version: v1.0.3 (installed via `git clone https://github.com/node-red/node-red.git` method)
Node.js version: v10.16.3

Thanks in advance for any idea that could help me solving this issue.
Cheers,

**Comment by milosjovac** [comment]
Have you install `libopenzwave1.5`? [Like shown in this thread](https://github.com/appmodule/node-red-contrib-openzwave-am/issues/3#issuecomment-547970239)

**Comment by Tazintosh** [comment]
Hi @milosjovac,
No I didn't found this anywhere on the documentation.
BTW, on the linked thread, you're saying "Or install it using the Node-Red Editor Palette" and this is exactly what I've done first.

Before, it was working. The only thing I remember having done in between, is uninstalling open-zwave from homebrew and installing it manually with git.

**Comment by Tazintosh** [comment]
Also, libopenzwave-1.6.dylib (in /usr/local/lib/) is installed when `make install` open-zwave Git

**Comment by milosjovac** [comment]
Hi @Tazintosh,
JFYI I tried to build new Docker image and was able to reproduce the problem. I will try to fix this in the next day or two.

**Comment by Tazintosh** [comment]
Great news, thanks @milosjovac!

**Comment by Tazintosh** [comment]
In case, this helps, a solution have been provided here:
https://discourse.nodered.org/t/cannot-get-node-red-contrib-openzwave-am-to-run/18246/17?u=tazintosh

**Comment by milosjovac** [comment]
Thanks @Tazintosh!

Proposed solution has been applied. There is a new version on `npm` - `1.5.10`.
